apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-web-app-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: nginx:latest
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 25
        pause: {}
      - setWeight: 50
        pause: {}
      - setWeight: 100
        pause: {}
